<?php

namespace EmotionBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllProductByCategory($id) {

        $qb = $this->createQueryBuilder('p');

        $qb
            ->where('p.category = :category')
            ->setParameter('category', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function findAllProductByBrand($id) {

        $qb = $this->createQueryBuilder('p');

        $qb
            ->where('p.brand = :brand')
            ->setParameter('brand', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
