<?php

namespace EmotionBundle\Repository;

/**
 * RentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentRepository extends \Doctrine\ORM\EntityRepository
{
	public function findUserById($id) {
		
        $qb = $this->createQueryBuilder('r');

        $qb
            ->where('r.id = :id')
            ->setParameter('id', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
