fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
emotion:
    resource: "@EmotionBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation